# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a43b10e6f1a97ebe20d14d8d12dd6be9"
name = "Craftify"
application_url = "https://craft-ify.vercel.app/"
embedded = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,write_files,read_inventory,read_locations,read_product_listings,write_product_listings,read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://craft-ify.vercel.app/api/shopify/callback" ]
